name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: sccache

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LD_LIBRARY_PATH: ${{ github.workspace }}/duckdb/build/debug/src/

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: hendrikmuhs/ccache-action@v1.2
      with:
        variant: sccache

    - name: Build
      run: cargo build --verbose

    - run: sudo apt install ninja-build build-essential
    - run: GEN=ninja make debug
      working-directory: duckdb

    - name: Compile tests
      run: cargo test --no-run --all-features

    - run: |
        pwd
        ls ${{ github.workspace }}/duckdb/build/debug/src/
        echo "LD_PRELOAD=$(whereis libasan.so.6 | cut -d ' ' -f 2)" >> $GITHUB_ENV

    - name: Run tests
      run: cargo test --verbose --all-features
