name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: sccache

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: hendrikmuhs/ccache-action@v1.2
      with:
        variant: sccache

    - name: Build
      run: cargo build --verbose

    - run: sudo apt install ninja-build build-essential
    - run: GEN=ninja make debug
      working-directory: duckdb

    - run: |
        pwd
        ls ${{ github.workspace }}/duckdb/build/debug/src/
        ls /usr/lib/gcc/x86_64-linux-gnu/11

    - name: Run tests
      run: cargo test --verbose --all-features
      env:
        LD_LIBRARY_PATH: ${{ github.workspace }}/duckdb/build/debug/src/
        LD_PRELOAD: /usr/lib/gcc/x86_64-linux-gnu/11/libasan.so
